Upstream tarball 20080905

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os RESOLV_LIB X11LIBS MULECPPFLAGS MULECFLAGS MULECXXFLAGS MULELDFLAGS MULERCFLAGS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP BUILD_CC ac_ct_BUILD_CC EXEEXT BUILD_EXEEXT BUILD_CPPFLAGS BUILD_CFLAGS BUILD_LDFLAGS EGREP LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB YACC AR ac_ct_AR LD ac_ct_LD ZLIB_CPPFLAGS ZLIB_LDFLAGS ZLIB_LIBS GDLIB_CONFIG_PATH GDLIB_CFLAGS GDLIB_LDFLAGS GDLIB_LIBS CAS_DEFS REGEX_LIBS LIBPNG_CONFIG_PATH LIBPNG_CFLAGS LIBPNG_LDFLAGS LIBPNG_LIBS AMULEWEB_DEFS GEOIP_CPPFLAGS GEOIP_LDFLAGS GEOIP_LIBS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION_FULL WX_RESCOMP WX_VERSION_MAJOR WX_VERSION_MINOR WX_UNICODE WX_DEBUG WX_SHARED WX_PORT WXBASE_LIBS WXBASE_CPPFLAGS RC RCFLAGS ac_ct_RC PKG_CONFIG ac_pt_PKG_CONFIG LIBUPNP_CPPFLAGS LIBUPNP_CFLAGS LIBUPNP_LDFLAGS LIBUPNP_LIBS CRYPTOPP_CPPFLAGS CRYPTOPP_LDFLAGS CRYPTOPP_LIBS BFD_CPPFLAGS BFD_LIBS ALLOCA LIBOBJS POW_LIB MKINSTALLDIRS MSGFMT GMSGFMT XGETTEXT MSGMERGE GLIBC21 LIBICONV LTLIBICONV INTLBISON USE_NLS BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT INTLOBJS DATADIRNAME INSTOBJEXT GENCAT INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB AMULE_DAEMON_MANPAGES AMULECMD_MANPAGES WEB_MANPAGES AMULE_GUI_MANPAGES CAS_MANPAGES WXCAS_MANPAGES ED2K_MANPAGES ALC_MANPAGES ALCC_MANPAGES MONOLITHIC_MANPAGES INCINTL docdir SVNDATE WEB_TRUE WEB_FALSE ED2K_TRUE ED2K_FALSE CAS_TRUE CAS_FALSE WXCAS_TRUE WXCAS_FALSE ALC_TRUE ALC_FALSE ALCC_TRUE ALCC_FALSE AMULE_GUI_TRUE AMULE_GUI_FALSE AMULE_DAEMON_TRUE AMULE_DAEMON_FALSE COMPILE_CMD_TRUE COMPILE_CMD_FALSE MONOLITHIC_TRUE MONOLITHIC_FALSE XAS_TRUE XAS_FALSE ENABLE_UPNP_TRUE ENABLE_UPNP_FALSE ENABLE_IP2COUNTRY_TRUE ENABLE_IP2COUNTRY_FALSE SYS_WIN32_TRUE SYS_WIN32_FALSE NEED_RC_TRUE NEED_RC_FALSE NEED_CORESERVICES_TRUE NEED_CORESERVICES_FALSE COMPILE_NLS_TRUE COMPILE_NLS_FALSE GENERATE_FLEX_HEADER_TRUE GENERATE_FLEX_HEADER_FALSE READLINE_LIBS LTLIBOBJS'
+ac_subst_vars='GEOIP_CPPFLAGS GEOIP_LDFLAGS GEOIP_LIBS SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os RESOLV_LIB X11LIBS MULECPPFLAGS MULECFLAGS MULECXXFLAGS MULELDFLAGS MULERCFLAGS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP BUILD_CC ac_ct_BUILD_CC EXEEXT BUILD_EXEEXT BUILD_CPPFLAGS BUILD_CFLAGS BUILD_LDFLAGS EGREP LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB YACC AR ac_ct_AR LD ac_ct_LD ZLIB_CPPFLAGS ZLIB_LDFLAGS ZLIB_LIBS GDLIB_CONFIG_PATH GDLIB_CFLAGS GDLIB_LDFLAGS GDLIB_LIBS CAS_DEFS REGEX_LIBS LIBPNG_CONFIG_PATH LIBPNG_CFLAGS LIBPNG_LDFLAGS LIBPNG_LIBS AMULEWEB_DEFS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION_FULL WX_RESCOMP WX_VERSION_MAJOR WX_VERSION_MINOR WX_UNICODE WX_DEBUG WX_SHARED WX_PORT WXBASE_LIBS WXBASE_CPPFLAGS RC RCFLAGS ac_ct_RC PKG_CONFIG ac_pt_PKG_CONFIG LIBUPNP_CPPFLAGS LIBUPNP_CFLAGS LIBUPNP_LDFLAGS LIBUPNP_LIBS CRYPTOPP_CPPFLAGS CRYPTOPP_LDFLAGS CRYPTOPP_LIBS BFD_CPPFLAGS BFD_LIBS ALLOCA LIBOBJS POW_LIB MKINSTALLDIRS MSGFMT GMSGFMT XGETTEXT MSGMERGE GLIBC21 LIBICONV LTLIBICONV INTLBISON USE_NLS BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT INTLOBJS DATADIRNAME INSTOBJEXT GENCAT INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB AMULE_DAEMON_MANPAGES AMULECMD_MANPAGES WEB_MANPAGES AMULE_GUI_MANPAGES CAS_MANPAGES WXCAS_MANPAGES ED2K_MANPAGES ALC_MANPAGES ALCC_MANPAGES MONOLITHIC_MANPAGES INCINTL docdir SVNDATE WEB_TRUE WEB_FALSE ED2K_TRUE ED2K_FALSE CAS_TRUE CAS_FALSE WXCAS_TRUE WXCAS_FALSE ALC_TRUE ALC_FALSE ALCC_TRUE ALCC_FALSE AMULE_GUI_TRUE AMULE_GUI_FALSE AMULE_DAEMON_TRUE AMULE_DAEMON_FALSE COMPILE_CMD_TRUE COMPILE_CMD_FALSE MONOLITHIC_TRUE MONOLITHIC_FALSE XAS_TRUE XAS_FALSE ENABLE_UPNP_TRUE ENABLE_UPNP_FALSE ENABLE_IP2COUNTRY_TRUE ENABLE_IP2COUNTRY_FALSE SYS_WIN32_TRUE SYS_WIN32_FALSE NEED_RC_TRUE NEED_RC_FALSE NEED_CORESERVICES_TRUE NEED_CORESERVICES_FALSE COMPILE_NLS_TRUE COMPILE_NLS_FALSE GENERATE_FLEX_HEADER_TRUE GENERATE_FLEX_HEADER_FALSE READLINE_LIBS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -909,10 +909,6 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-geoip-headers=DIR
-                          GeoIP include files location
-  --with-geoip-lib=DIR    GeoIP library location
-  --with-geoip-static     Explicitly link GeoIP statically (default=no)
   --without-gnu-malloc    Don't assume that we use GNU libc compatible
                           malloc/realloc when cross-compiling
   --with-zlib=PREFIX      use zlib in PREFIX
@@ -924,6 +920,10 @@ Optional Packages:
                           prefix where libpng is installed (optional)
   --with-libpng-config=CONFIG
                           libpng-config script to use (optional)
+  --with-geoip-headers=DIR
+                          GeoIP include files location
+  --with-geoip-lib=DIR    GeoIP library location
+  --with-geoip-static     Explicitly link GeoIP statically (default=no)
   --with-wxdir=PATH       Use uninstalled version of wxWidgets in PATH
   --with-wx-config=CONFIG wx-config script to use (optional)
   --with-wx-prefix=PREFIX Prefix where wxWidgets is installed (optional)
@@ -5537,43 +5537,6 @@ else
   XAS=yes
 fi;
 
-# Check whether --enable-geoip or --disable-geoip was given.
-if test "${enable_geoip+set}" = set; then
-  enableval="$enable_geoip"
-  ENABLE_IP2COUNTRY=$enableval
-else
-  ENABLE_IP2COUNTRY=no
-fi;
-
-if test ${ENABLE_IP2COUNTRY:-no} = yes; then
-  GEOIP_LIBS="-lGeoIP"
-fi
-
-
-
-# Check whether --with-geoip-headers or --without-geoip-headers was given.
-if test "${with_geoip_headers+set}" = set; then
-  withval="$with_geoip_headers"
-  GEOIP_CPPFLAGS="-I$withval"
-fi;
-
-
-# Check whether --with-geoip-lib or --without-geoip-lib was given.
-if test "${with_geoip_lib+set}" = set; then
-  withval="$with_geoip_lib"
-  GEOIP_LDFLAGS="-L$withval"
-fi;
-
-
-# Check whether --with-geoip-static or --without-geoip-static was given.
-if test "${with_geoip_static+set}" = set; then
-  withval="$with_geoip_static"
-  if test "$withval" != "no"; then
-  GEOIP_LIBS="-Wl,-Bstatic $GEOIP_LIBS -Wl,-Bdynamic"
-fi
-
-fi;
-
 # Default is yes, because they're most likely compatible.
 # However, this is only used when cross-compiling.
 
@@ -7111,14 +7074,39 @@ echo "${ECHO_T}$need_gui" >&6
 
 
 # Check for GeoIP (required for IP2Country capability)
-if test ${ENABLE_IP2COUNTRY:-no} = yes; then
 
-	GEOIP_CPPFLAGS="$GEOIP_CPPFLAGS -DENABLE_IP2COUNTRY=1"
-	mule_backup_CPPFLAGS="$CPPFLAGS"
-	CPPFLAGS="$CPPFLAGS $GEOIP_CPPFLAGS"
-	mule_backup_LDFLAGS="$LDFLAGS"
-	LDFLAGS="$LDFLAGS $GEOIP_LDFLAGS"
-	if test "${ac_cv_header_GeoIP_h+set}" = set; then
+	# Check whether --enable-geoip or --disable-geoip was given.
+if test "${enable_geoip+set}" = set; then
+  enableval="$enable_geoip"
+  ENABLE_IP2COUNTRY=$enableval
+else
+  ENABLE_IP2COUNTRY=no
+fi;
+
+	if test ${ENABLE_IP2COUNTRY:-no} = yes; then
+
+		GEOIP_LIBS="-lGeoIP"
+
+
+# Check whether --with-geoip-headers or --without-geoip-headers was given.
+if test "${with_geoip_headers+set}" = set; then
+  withval="$with_geoip_headers"
+  GEOIP_CPPFLAGS="-I$withval"
+fi;
+
+
+# Check whether --with-geoip-lib or --without-geoip-lib was given.
+if test "${with_geoip_lib+set}" = set; then
+  withval="$with_geoip_lib"
+  GEOIP_LDFLAGS="-L$withval"
+fi;
+
+		GEOIP_CPPFLAGS="$GEOIP_CPPFLAGS -DENABLE_IP2COUNTRY=1"
+		mule_backup_CPPFLAGS="$CPPFLAGS"
+		CPPFLAGS="$CPPFLAGS $GEOIP_CPPFLAGS"
+		mule_backup_LDFLAGS="$LDFLAGS"
+		LDFLAGS="$LDFLAGS $GEOIP_LDFLAGS"
+		if test "${ac_cv_header_GeoIP_h+set}" = set; then
   echo "$as_me:$LINENO: checking for GeoIP.h" >&5
 echo $ECHO_N "checking for GeoIP.h... $ECHO_C" >&6
 if test "${ac_cv_header_GeoIP_h+set}" = set; then
@@ -7256,15 +7244,8 @@ echo "${ECHO_T}$ac_cv_header_GeoIP_h" >&6
 
 fi
 if test $ac_cv_header_GeoIP_h = yes; then
-  :
-else
-  { { echo "$as_me:$LINENO: error: --enable-geoip passed to configure, but the GeoIP header files were not found" >&5
-echo "$as_me: error: --enable-geoip passed to configure, but the GeoIP header files were not found" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
-
-	echo "$as_me:$LINENO: checking for GeoIP_open in -lGeoIP" >&5
+			echo "$as_me:$LINENO: checking for GeoIP_open in -lGeoIP" >&5
 echo $ECHO_N "checking for GeoIP_open in -lGeoIP... $ECHO_C" >&6
 if test "${ac_cv_lib_GeoIP_GeoIP_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -7330,18 +7311,126 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_GeoIP_GeoIP_open" >&5
 echo "${ECHO_T}$ac_cv_lib_GeoIP_GeoIP_open" >&6
 if test $ac_cv_lib_GeoIP_GeoIP_open = yes; then
 
+
 cat >>confdefs.h <<\_ACEOF
 #define SUPPORT_GEOIP 1
 _ACEOF
 
+
+# Check whether --with-geoip-static or --without-geoip-static was given.
+if test "${with_geoip_static+set}" = set; then
+  withval="$with_geoip_static"
+
+					if test "$withval" != "no" -a ${enable_static:-no} = no; then
+
+						mule_backup_LIBS="$LIBS"
+						LIBS="-Wl,-Bstatic $GEOIP_LIBS -Wl,-Bdynamic $LIBS"
+						cat >conftest.$ac_ext <<_ACEOF
+
+							/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+								#include <GeoIP.h>
+
+int
+main ()
+{
+
+								GeoIP *g = GeoIP_new(GEOIP_STANDARD);
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+							GEOIP_LIBS="-Wl,-Bstatic $GEOIP_LIBS -Wl,-Bdynamic"
+
 else
-  { { echo "$as_me:$LINENO: error: --enable-geoip passed to configure, but the GeoIP libraries were not found" >&5
-echo "$as_me: error: --enable-geoip passed to configure, but the GeoIP libraries were not found" >&2;}
-   { (exit 1); exit 1; }; }
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+							{ echo "$as_me:$LINENO: WARNING:
+        Cannot link GeoIP statically, because your linker ($LD) does not
+        support it." >&5
+echo "$as_me: WARNING:
+        Cannot link GeoIP statically, because your linker ($LD) does not
+        support it." >&2;}
+_mule_warning_3=yes
+_mule_has_warnings=yes
+
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+						LIBS="$mule_backup_LIBS"
+
 fi
 
-	CPPFLAGS="$mule_backup_CPPFLAGS"
-	LDFLAGS="$mule_backup_LDFLAGS"
+
+fi;
+
+else
+
+				ENABLE_IP2COUNTRY=disabled
+				{ echo "$as_me:$LINENO: WARNING:
+        GeoIP support has been disabled because the GeoIP libraries were not
+        found" >&5
+echo "$as_me: WARNING:
+        GeoIP support has been disabled because the GeoIP libraries were not
+        found" >&2;}
+_mule_warning_4=yes
+_mule_has_warnings=yes
+
+
+fi
+
+
+else
+
+			ENABLE_IP2COUNTRY=disabled
+			{ echo "$as_me:$LINENO: WARNING:
+        GeoIP support has been disabled because the GeoIP header files were
+        not found" >&5
+echo "$as_me: WARNING:
+        GeoIP support has been disabled because the GeoIP header files were
+        not found" >&2;}
+_mule_warning_5=yes
+_mule_has_warnings=yes
+
+
+fi
+
+
+
+		CPPFLAGS="$mule_backup_CPPFLAGS"
+		LDFLAGS="$mule_backup_LDFLAGS"
 
 fi
 
@@ -8353,7 +8442,7 @@ else
         UPnP code has been disabled because ${libupnp_error}." >&5
 echo "$as_me: WARNING:
         UPnP code has been disabled because ${libupnp_error}." >&2;}
-_mule_warning_3=yes
+_mule_warning_6=yes
 _mule_has_warnings=yes
 
 
@@ -8641,7 +8730,7 @@ echo "$as_me: WARNING:
         Cross-compilation detected, so exception handling cannot be tested.
         Note that broken exception handling in your compiler may lead to
         unexpected crashes." >&2;}
-_mule_warning_4=yes
+_mule_warning_7=yes
 _mule_has_warnings=yes
 
 
@@ -8849,7 +8938,7 @@ echo "${ECHO_T}no" >&6
 echo "$as_me: WARNING:
         bfd.h not found or unusable, please install binutils development
         package if you are a developer or want to help testing aMule" >&2;}
-_mule_warning_5=yes
+_mule_warning_8=yes
 _mule_has_warnings=yes
 
 
@@ -14088,7 +14177,7 @@ echo "$as_me: WARNING:
         configure cannot check whether malloc() and realloc() are GNU libc
         compatible. You have to be ABSOLUTELY sure that they are, otherwise
         run configure with the --without-gnu-malloc switch." >&2;}
-_mule_warning_6=yes
+_mule_warning_9=yes
 _mule_has_warnings=yes
 
 	ac_cv_func_malloc_0_nonnull=yes
@@ -18154,7 +18243,7 @@ fi
 echo "$as_me: WARNING:
         You need to install GNU gettext/gettext-tools to compile aMule with
         i18n support." >&2;}
-_mule_warning_7=yes
+_mule_warning_10=yes
 _mule_has_warnings=yes
 
 fi
@@ -20110,6 +20199,9 @@ if test -n "\$CONFIG_FILES"; then
   # Protect against being on the right side of a sed subst in config.status.
   sed 's/,@/@@/; s/@,/@@/; s/,;t t\$/@;t t/; /@;t t\$/s/[\\\\&,]/\\\\&/g;
    s/@@/,@/; s/@@/@,/; s/@;t t\$/,;t t/' >\$tmp/subs.sed <<\\CEOF
+s,@GEOIP_CPPFLAGS@,$GEOIP_CPPFLAGS,;t t
+s,@GEOIP_LDFLAGS@,$GEOIP_LDFLAGS,;t t
+s,@GEOIP_LIBS@,$GEOIP_LIBS,;t t
 s,@SHELL@,$SHELL,;t t
 s,@PATH_SEPARATOR@,$PATH_SEPARATOR,;t t
 s,@PACKAGE_NAME@,$PACKAGE_NAME,;t t
@@ -20236,9 +20328,6 @@ s,@LIBPNG_CFLAGS@,$LIBPNG_CFLAGS,;t t
 s,@LIBPNG_LDFLAGS@,$LIBPNG_LDFLAGS,;t t
 s,@LIBPNG_LIBS@,$LIBPNG_LIBS,;t t
 s,@AMULEWEB_DEFS@,$AMULEWEB_DEFS,;t t
-s,@GEOIP_CPPFLAGS@,$GEOIP_CPPFLAGS,;t t
-s,@GEOIP_LDFLAGS@,$GEOIP_LDFLAGS,;t t
-s,@GEOIP_LIBS@,$GEOIP_LIBS,;t t
 s,@WX_CONFIG_PATH@,$WX_CONFIG_PATH,;t t
 s,@WX_CPPFLAGS@,$WX_CPPFLAGS,;t t
 s,@WX_CFLAGS@,$WX_CFLAGS,;t t
@@ -21262,6 +21351,16 @@ fi
 
 echo "                                       libintl               $libintl_found"
 fi
+if test -z "${with_geoip_headers:-}${with_geoip_lib:-}"; then
+  geoip_style=system
+else
+  geoip_style=user
+fi
+
+if test ${ENABLE_IP2COUNTRY:-no} = yes; then
+  echo "                                       libGeoIP              ${geoip_style}"
+fi
+
 if test x$LIBPNG_VERSION != xnot_needed; then
 echo "                                       libpng                ${LIBPNG_VERSION:-Not detected}"
 fi
@@ -21305,10 +21404,29 @@ fi
 if test ${_mule_warning_3:-no} = yes; then
 cat <<_MULEEOT
 
-* UPnP code has been disabled because ${libupnp_error}.
+* Cannot link GeoIP statically, because your linker ($LD) does not support it.
 _MULEEOT
 fi
 if test ${_mule_warning_4:-no} = yes; then
+cat <<_MULEEOT
+
+* GeoIP support has been disabled because the GeoIP libraries were not found
+_MULEEOT
+fi
+if test ${_mule_warning_5:-no} = yes; then
+cat <<_MULEEOT
+
+* GeoIP support has been disabled because the GeoIP header files were not
+  found
+_MULEEOT
+fi
+if test ${_mule_warning_6:-no} = yes; then
+cat <<_MULEEOT
+
+* UPnP code has been disabled because ${libupnp_error}.
+_MULEEOT
+fi
+if test ${_mule_warning_7:-no} = yes; then
 cat <<_MULEEOT
 
 * Cross-compilation detected, so exception handling cannot be tested.
@@ -21316,14 +21434,14 @@ cat <<_MULEEOT
   crashes.
 _MULEEOT
 fi
-if test ${_mule_warning_5:-no} = yes; then
+if test ${_mule_warning_8:-no} = yes; then
 cat <<_MULEEOT
 
 * bfd.h not found or unusable, please install binutils development package if
   you are a developer or want to help testing aMule
 _MULEEOT
 fi
-if test ${_mule_warning_6:-no} = yes; then
+if test ${_mule_warning_9:-no} = yes; then
 cat <<_MULEEOT
 
 * configure cannot check whether malloc() and realloc() are GNU libc
@@ -21331,7 +21449,7 @@ cat <<_MULEEOT
   configure with the --without-gnu-malloc switch.
 _MULEEOT
 fi
-if test ${_mule_warning_7:-no} = yes; then
+if test ${_mule_warning_10:-no} = yes; then
 cat <<_MULEEOT
 
 * You need to install GNU gettext/gettext-tools to compile aMule with i18n
