Upstream tarball 9546

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6870,11 +6870,6 @@ fi;
 		mule_backup_LDFLAGS="$LDFLAGS"
 		LDFLAGS="$LDFLAGS $GEOIP_LDFLAGS"
 
-       		if test x$SYS = xwin32; then
-  OTHERLIBS="-lws2_32"
-fi
-
-
 		if test "${ac_cv_header_GeoIP_h+set}" = set; then
   echo "$as_me:$LINENO: checking for GeoIP.h" >&5
 echo $ECHO_N "checking for GeoIP.h... $ECHO_C" >&6
@@ -7014,13 +7009,81 @@ echo "${ECHO_T}$ac_cv_header_GeoIP_h" >&6
 fi
 if test $ac_cv_header_GeoIP_h = yes; then
 
+			if test x$SYS = xwin32; then
+
+				echo "$as_me:$LINENO: checking for WinSock library needed by GeoIP" >&5
+echo $ECHO_N "checking for WinSock library needed by GeoIP... $ECHO_C" >&6
+				# Actually, we might not need any if GeoIP is linked as a .dll
+				# - but that's even harder to check for
+				cat >conftest.$ac_ext <<_ACEOF
+
+					/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+						#include <GeoIP.h>
+						#ifdef _WINSOCK2_H
+							I do know it's not the best approach, but at least works with MinGW stock headers.
+							(tested with w32api-3.12)
+						#endif
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+					GEOIP_WINSOCK_LIB="-lwsock32"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+					GEOIP_WINSOCK_LIB="-lws2_32"
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+				echo "$as_me:$LINENO: result: $GEOIP_WINSOCK_LIB" >&5
+echo "${ECHO_T}$GEOIP_WINSOCK_LIB" >&6
+
+fi
+
 			echo "$as_me:$LINENO: checking for GeoIP_open in -lGeoIP" >&5
 echo $ECHO_N "checking for GeoIP_open in -lGeoIP... $ECHO_C" >&6
 if test "${ac_cv_lib_GeoIP_GeoIP_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lGeoIP ${OTHERLIBS:-} $LIBS"
+LIBS="-lGeoIP ${GEOIP_WINSOCK_LIB:-} $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -7087,7 +7150,7 @@ _ACEOF
 
 				GEOIP_LIBS="-lGeoIP"
 				if test x$SYS = xwin32; then
-  GEOIP_LIBS="$GEOIP_LIBS -lws2_32"
+  GEOIP_LIBS="$GEOIP_LIBS $GEOIP_WINSOCK_LIB"
 fi
 
 				GEOIP_CPPFLAGS="$GEOIP_CPPFLAGS -DENABLE_IP2COUNTRY=1"
